### ISSUE TITLE
Failed to Run

### ISSUE THREAD

**Issue by malikahmedraza** [beginor/ng-esri-demo#5]
I followed the instructions as given in usage but failed to run this example. It fails to compile with the following errors.

ERROR in src/app/components/home/home.component.ts(4,24): error TS2307: Cannot find module 'ng-animations'.
src/app/components/map-view/map-view.component.ts(9,23): error TS2307: Cannot find module 'esri-service'.
src/app/components/map-view/map-view.component.ts(11,24): error TS2307: Cannot find module 'ng-animations'.

**Comment by beginor** [comment]
This repo has 2 sub pbojects, please run `npm run build ng-animations` and `npm run build esri-service` first

**Comment by malikahmedraza** [comment]
Great, thanks for the help. I will close this issue. 

But I will suggest to keep the sub projects part of repo.
