### ISSUE TITLE
Issue when the Map View is created

### ISSUE THREAD

**Issue by warleymendes** [beginor/ng-esri-demo#6]
Issue when the map is created.

```
const map = await esri.createMap({
   basemap: 'satellite',
    ground: 'world-elevation'
 });
```

Error message:

`dojo.js:346 [esri.views.LayerViewFactory] Failed to create view for layer 'Terrain3D, id:worldElevation' of type 'elevation'.`

**Comment by beginor** [comment]
`ground` is not supported in `MapView`， do not use the property when using `MapView`, I will update the demo to fix this issue when I hive time.
