### ISSUE TITLE
Issue when the user chooses a basemap

### ISSUE THREAD

**Issue by warleymendes** [beginor/ng-esri-demo#7]
The map does not show anything when the user chooses a base map using the BasemapsGallery widget.

File: map-view.component.ts
```
const gallery = await esri.createBasemapsGallery(
   {
       view: this.mapView,
       source: localSource
    },
    {
       expandTooltip: '底图'
    }
 );
```

Error message:
`[esri.views.LayerViewFactory] Failed to create view for layer 'null, id:16c02536e7c-layer-0' of type 'null'`

**Comment by beginor** [comment]
Can not find how to init base map gallery with local source in scene view, just remove it.
