### ISSUE TITLE
browser memory is not reduced

### ISSUE THREAD

**Issue by cuiwenting** [beginor/ng-esri-demo#8]
After the map was created, I found that the browser memory grew, and the memory did not drop when the route was switched.In other words, the map was destroyed without freeing all memory.

**Comment by beginor** [comment]
You can call the `destroy` method of `mapView` or `sceneView` on `ngOnDestroy` method, like this:

```ts
public ngOnDestroy(): void {
    this.mapView.destroy();
}
```
